apiVersion: v1
kind: Service
metadata:
  name: speedtest-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    #chapter: services
    app: speedtest-app
  externalIPs:
  - 192.168.66.251
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedtest-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: speedtest-app
    spec:
      containers:
      - name: speedtest-app
        image: git.internal.keepingpacetech.com/kweevuss/speedtest:latest
        ports:
        - containerPort: 80